.\" Man page for image segmentation
.\" David Gold 4/15/18
.TH Image Segmentation  1 "15 May 2018" "CSCI 241" "Oberlin College"

.SH NAME
.B K-Means Image Segmentation
\- An unsupervised clustering algorithm.
.SH SYNOPSIS
.B ImageSegmentation
.SH DESCRIPTION
 Program takes a user input and a number of groups then clusters the images into groups based off X location, Y location, and R,G,B vals.
.SP
 ./ImageSegmentation infile.jpeg K outfile.jpeg
.SH OPTIONS
Program takes user input for an image file to decompress, an int for number of groups for the image, and the name of the output file (optional).  
.SH AUTHOR
David Gold Lars Dreith Leo Schumann Jiachen Liu (Spring 2018)
.SH BUGS
No bugs!

